[package]
name = "genetta_audio_streaming"
version = "0.1.0"
edition = "2021"

[lib]
name = "GenettaAudioStreaming"
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time"] }
once_cell = "1.19"
bytes = "1.6"